export const categories = [
  { value: 'fashion', label: 'Clothing & Apparel' },
  { value: 'electronics', label: 'Electronics & Gadgets' },
  { value: 'home_kitchen', label: 'Home & Kitchen' },
  { value: 'beauty', label: 'Beauty & Personal Care' },
  { value: 'sports', label: 'Sports & Outdoors' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'books', label: 'Books & Stationery' },
  { value: 'toys', label: 'Toys & Games' },
  { value: 'furniture', label: 'Furniture' },
  { value: 'groceries', label: 'Groceries & Essentials' },
  { value: 'health', label: 'Health & Wellness' },
  { value: 'jewelry', label: 'Jewelry & Accessories' },
  { value: 'footwear', label: 'Footwear' },
  { value: 'bags', label: 'Bags & Luggage' },
  { value: 'watches', label: 'Watches' },
  { value: 'mobile_accessories', label: 'Mobile Accessories' },
  { value: 'computers', label: 'Computers & Laptops' },
  { value: 'gaming', label: 'Gaming & Consoles' },
  { value: 'baby_products', label: 'Baby Products' },
  { value: 'pet_supplies', label: 'Pet Supplies' },
  { value: 'office_supplies', label: 'Office Supplies' },
  { value: 'garden', label: 'Garden & Outdoor' },
  { value: 'musical_instruments', label: 'Musical Instruments' },
  { value: 'home_decor', label: 'Home Decor' },
  { value: 'appliances', label: 'Home Appliances' },
  { value: 'fitness', label: 'Fitness Equipment' },
  { value: 'travel', label: 'Travel & Accessories' },
  { value: 'crafts', label: 'Arts & Crafts' },
  { value: 'industrial', label: 'Industrial & Tools' },
  { value: 'digital_products', label: 'Digital Products' },
];
